"""跨服务 backend-auth 鉴权与用户上下文客户端。"""

from auth_utils.client import (
    AuthClient,
    AuthenticatedUser,
    AuthenticationError,
    AuthorizationError,
    AuthServiceUnavailableError,
)
from auth_utils.domain import (
    ADMIN_ROLE_CODES,
    AVATAR_CONTENT_TYPES,
    AVATAR_MAX_SIZE_BYTES,
    BUSINESS_VIP_LEVELS,
    FULL_ACCESS_ROLE_CODES,
    INVITE_CODE_ALLOWED_PATTERN,
    INVITE_CODE_GENERATED_LENGTH,
    INVITE_CODE_MAX_LENGTH,
    INVITE_CODE_MIN_LENGTH,
    PROTECTED_ROLE_CODES,
    ROLE_CODE_MANAGER,
    ROLE_CODE_SUPER_ADMIN,
    ROLE_CODE_USER,
    USER_PROFILE_ROUTE_PATH,
    MenuType,
    VipLevel,
    detect_avatar_content_type,
    get_vip_display,
    is_business_vip_level,
)
from auth_utils.permissions import PermissionCode

__all__ = [
    "ADMIN_ROLE_CODES",
    "AVATAR_CONTENT_TYPES",
    "AVATAR_MAX_SIZE_BYTES",
    "AuthClient",
    "AuthenticatedUser",
    "AuthenticationError",
    "AuthorizationError",
    "AuthServiceUnavailableError",
    "BUSINESS_VIP_LEVELS",
    "FULL_ACCESS_ROLE_CODES",
    "INVITE_CODE_ALLOWED_PATTERN",
    "INVITE_CODE_GENERATED_LENGTH",
    "INVITE_CODE_MAX_LENGTH",
    "INVITE_CODE_MIN_LENGTH",
    "MenuType",
    "PermissionCode",
    "PROTECTED_ROLE_CODES",
    "ROLE_CODE_MANAGER",
    "ROLE_CODE_SUPER_ADMIN",
    "ROLE_CODE_USER",
    "USER_PROFILE_ROUTE_PATH",
    "VipLevel",
    "detect_avatar_content_type",
    "get_vip_display",
    "is_business_vip_level",
]
