from __future__ import annotations

"""提供商特定字段定义模块，提供各 AI 提供商的参数配置结构。"""

from typing import Any


PROVIDER_PARAM_SCHEMAS: dict[str, dict[str, Any]] = {
    "openai": {
        "description": "OpenAI Responses / Chat 参数",
        "fields": [
            {
                "key": "reasoning_effort",
                "label": "思考强度",
                "kind": "select",
                "options": ["low", "medium", "high"],
                "placeholder": "按需设置",
                "help": "模型思考强度，需 o1/o3 等支持 reasoning 的模型。",
            },
            {
                "key": "verbosity",
                "label": "回答冗长度",
                "kind": "select",
                "options": ["low", "medium", "high"],
                "placeholder": "按需设置",
                "help": "仅对支持 verbosity 的 OpenAI 模型生效。",
            },
            {
                "key": "top_p",
                "label": "Top P",
                "kind": "number",
                "min": 0,
                "max": 1,
                "step": 0.1,
                "help": "采样概率质量阈值。",
            },
            {
                "key": "presence_penalty",
                "label": "存在惩罚",
                "kind": "number",
                "min": -2,
                "max": 2,
                "step": 0.1,
                "help": "正值根据新 token 在文本中的出现频率进行惩罚。",
            },
            {
                "key": "frequency_penalty",
                "label": "频率惩罚",
                "kind": "number",
                "min": -2,
                "max": 2,
                "step": 0.1,
                "help": "正值根据 token 在文本中的现有频率进行惩罚。",
            },
            {
                "key": "__builtin_tools__",
                "label": "内置工具",
                "kind": "builtin_tools",
                "help": "启用后模型可调用 OpenAI 内置工具（需 Responses API 支持）。",
            },
        ],
    },
    "openai_compatible": {
        "description": "自定义 / 本地模型参数（OpenAI 兼容）",
        "fields": [
            {
                "key": "reasoning_effort",
                "label": "思考强度",
                "kind": "select",
                "options": ["low", "medium", "high"],
                "placeholder": "按需设置",
                "help": "模型思考强度，需模型支持 reasoning 相关能力。",
            },
            {
                "key": "top_p",
                "label": "Top P",
                "kind": "number",
                "min": 0,
                "max": 1,
                "step": 0.1,
                "help": "采样概率质量阈值。",
            },
            {
                "key": "presence_penalty",
                "label": "存在惩罚",
                "kind": "number",
                "min": -2,
                "max": 2,
                "step": 0.1,
                "help": "正值根据新 token 在文本中的出现频率进行惩罚。",
            },
            {
                "key": "frequency_penalty",
                "label": "频率惩罚",
                "kind": "number",
                "min": -2,
                "max": 2,
                "step": 0.1,
                "help": "正值根据 token 在文本中的现有频率进行惩罚。",
            },
            {
                "key": "top_k",
                "label": "Top K",
                "kind": "integer",
                "min": 1,
                "max": 500,
                "step": 1,
                "help": "模型从概率最高的 K 个 token 中选择。",
            },
            {
                "key": "seed",
                "label": "随机种子",
                "kind": "integer",
                "min": 0,
                "max": 9999999999,
                "step": 1,
                "help": "设置后相同 seed 和输入会返回相同输出。",
            },
            {
                "key": "stop",
                "label": "停止序列",
                "kind": "text",
                "placeholder": "留空或输入停止文本",
                "help": "遇到此文本时停止生成，可多个。",
            },
            {
                "key": "response_format",
                "label": "响应格式",
                "kind": "select",
                "options": ["", "text", "json_object"],
                "placeholder": "按需设置",
                "help": "text=普通文本，json_object=JSON 对象（需提示词配合）。",
            },
            {
                "key": "logit_bias",
                "label": "Token 偏置",
                "kind": "text",
                "placeholder": "留空或输入 JSON，如：{\"50256\": -100}",
                "help": "调整特定 token 的生成概率，格式：{\"token_id\": 偏置值}。",
            },
            {
                "key": "user",
                "label": "用户标识",
                "kind": "text",
                "placeholder": "留空或输入唯一标识",
                "help": "用于标识终端用户的唯一标识符，便于内容过滤和滥用检测。",
            },
            {
                "key": "__builtin_tools__",
                "label": "内置工具",
                "kind": "builtin_tools",
                "help": "启用后模型可调用 OpenAI 内置工具（需 Responses API 支持）。",
            },
        ],
    },
    "deepseek": {
        "description": "DeepSeek OpenAI 兼容参数",
        "fields": [
            {
                "key": "reasoning_effort",
                "label": "思考强度",
                "kind": "select",
                "options": ["low", "medium", "high"],
                "placeholder": "按需设置",
                "help": "模型思考强度，需 DeepSeek-R1 等支持 reasoning 的模型。",
            },
            {
                "key": "top_p",
                "label": "Top P",
                "kind": "number",
                "min": 0,
                "max": 1,
                "step": 0.1,
            },
            {
                "key": "presence_penalty",
                "label": "存在惩罚",
                "kind": "number",
                "min": -2,
                "max": 2,
                "step": 0.1,
            },
            {
                "key": "frequency_penalty",
                "label": "频率惩罚",
                "kind": "number",
                "min": -2,
                "max": 2,
                "step": 0.1,
            },
        ],
    },
    "moonshot": {
        "description": "Moonshot Kimi OpenAI 兼容参数",
        "fields": [
            {
                "key": "reasoning_effort",
                "label": "思考强度",
                "kind": "select",
                "options": ["low", "medium", "high"],
                "placeholder": "按需设置",
                "help": "模型思考强度，需 Kimi 等支持 reasoning 的模型。",
            },
            {
                "key": "top_p",
                "label": "Top P",
                "kind": "number",
                "min": 0,
                "max": 1,
                "step": 0.1,
            },
            {
                "key": "presence_penalty",
                "label": "存在惩罚",
                "kind": "number",
                "min": -2,
                "max": 2,
                "step": 0.1,
            },
            {
                "key": "frequency_penalty",
                "label": "频率惩罚",
                "kind": "number",
                "min": -2,
                "max": 2,
                "step": 0.1,
            },
        ],
    },
    "dashscope": {
        "description": "DashScope 通义千问参数",
        "fields": [
            {
                "key": "reasoning_effort",
                "label": "思考强度",
                "kind": "select",
                "options": ["low", "medium", "high"],
                "placeholder": "按需设置",
                "help": "模型思考强度，需 Qwq 等支持 reasoning 的模型。",
            },
            {
                "key": "top_p",
                "label": "Top P",
                "kind": "number",
                "min": 0,
                "max": 1,
                "step": 0.1,
                "help": "Tongyi 官方 LangChain 集成显式支持 top_p。",
            },
        ],
    },
    "claude": {
        "description": "Anthropic Claude 参数",
        "fields": [
            {
                "key": "top_p",
                "label": "Top P",
                "kind": "number",
                "min": 0,
                "max": 1,
                "step": 0.1,
            },
            {
                "key": "top_k",
                "label": "Top K",
                "kind": "integer",
                "min": 1,
                "max": 500,
                "step": 1,
                "help": "模型从概率最高的 K 个 token 中选择。",
            },
        ],
    },
    "gemini": {
        "description": "Google Gemini 参数",
        "fields": [
            {
                "key": "top_p",
                "label": "Top P",
                "kind": "number",
                "min": 0,
                "max": 1,
                "step": 0.1,
            },
            {
                "key": "top_k",
                "label": "Top K",
                "kind": "integer",
                "min": 1,
                "max": 100,
                "step": 1,
                "help": "模型从概率最高的 K 个 token 中选择。",
            },
        ],
    },
    "zhipu": {
        "description": "智谱 GLM 参数",
        "fields": [
            {
                "key": "reasoning_effort",
                "label": "思考强度",
                "kind": "select",
                "options": ["low", "medium", "high"],
                "placeholder": "按需设置",
                "help": "模型思考强度，需 GLM-4 等支持 reasoning 的模型。",
            },
            {
                "key": "top_p",
                "label": "Top P",
                "kind": "number",
                "min": 0,
                "max": 1,
                "step": 0.1,
            },
        ],
    },
    "minimax": {
        "description": "MiniMax 参数",
        "fields": [
            {
                "key": "reasoning_effort",
                "label": "思考强度",
                "kind": "select",
                "options": ["low", "medium", "high"],
                "placeholder": "按需设置",
                "help": "模型思考强度，需支持 reasoning 的模型。",
            },
            {
                "key": "top_p",
                "label": "Top P",
                "kind": "number",
                "min": 0,
                "max": 1,
                "step": 0.1,
            },
        ],
    },
}


def get_provider_param_schemas() -> dict[str, Any]:
    return PROVIDER_PARAM_SCHEMAS
